modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "tfcweldbutton"
version = "${file.jarVersion}"
displayName = "TFC Weld Button"
authors = "HermitOwO"
description = '''TFC Weld Button'''

[[dependencies.tfcweldbutton]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfcweldbutton]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfcweldbutton]]
modId = "tfc"
mandatory = true
versionRange = "[3.0.0-beta,)"
ordering = "NONE"
side = "BOTH"